CREATE TABLE VOTO (
    ID INT NOT NULL AUTO_INCREMENT,
    TIPO_VOTO VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PAUTA(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DATA_INICIO TIMESTAMP NOT NULL,
    DATA_FIM TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);
