spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  datasource:
    username: sa
    password: password
    url: jdbc:h2:file:~/votoDB;IFEXISTS=FALSE;
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

server:
  servlet:
    context-path: /api