spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MYSQL


  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false