spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  datasource:
    username: sa
    password: password
    url: jdbc:h2:file:~/votoDB;IFEXISTS=FALSE;
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

springfox:
  documentation:
    enabled: true

server:
  servlet:
    context-path: /api

api:
  cpf:
    url: https://user-info.herokuapp.com/users
